on:
  push:
    branches:
      - "**"

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: ${{github.ref_name}}
    steps:
      - run: |
          [[ "$GITHUB_REF" =~ ^refs/heads/deploy/(.*)$ ]] && \
          echo "WORKSPACE_NAME=${BASH_REMATCH[1]}" > "$GITHUB_ENV"
      - uses: actions/checkout@v2.4.0
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::223121549624:role/hhvm-packaging-github-actions
          aws-region: us-west-2
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init
      - run: terraform workspace select "$WORKSPACE_NAME" || terraform workspace new "$WORKSPACE_NAME"
      - run: terraform apply -auto-approve
      - if: github.ref_type == 'branch'
        uses: peter-evans/create-pull-request@v4
        with:
          branch: create-pull-request/${{github.ref_name}}